Removed the require => Class['logrotate::base'] to avoid dependency cycles issues when overriding values on Foreman
 --------------
 Info: Applying configuration version '1438371158'
 Error: Could not apply complete catalog: Found 1 dependency cycle:
 (File[/etc/logrotate.d/messages] => Logrotate::Rule[messages] => Class[Logrotate] => File[/etc/logrotate.d/messages])
 Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
 Notice: Finished catalog run in 0.08 seconds
 --------------